import './global.css';
import { ReactNode, Suspense } from 'react';
import { Providers } from './providers';
import { Navbar } from '@/components/Navbar';
import { NavigationEvents } from '@/services/NavigationEvents';

export const metadata = {
  title: 'Run App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className="s:text-xs sm:text-sm md:text-base lg:text-lg 2xl:text-2xl"
    >
      <body>
        <Providers>
          <Navbar />
          {/* <Home /> */}
          {children}
          {/* <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense> */}
        </Providers>
      </body>
    </html>
  );
}
