import './global.css';

import { ReactNode, Suspense } from 'react';
import localFont from 'next/font/local';
import { Inter, Orbitron,  Share_Tech_Mono, Nanum_Myeongjo, } from 'next/font/google';

import { Providers } from './providers';
import { Navbar } from '@/components/Navbar';
import { NavigationEvents } from '@/services/NavigationEvents';

export const metadata = {
  title: 'Run App',
  description: 'Generated by create next app',
};

const wideFont = localFont({
  src: [
    {
      path: '../../public/fonts/LibertadMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    // {
    //   path: '../../public/fonts/MTSWideMedium.woff2',
    //   weight: '700',
    //   style: 'normal',
    // },
  ],
  display: 'fallback',
});
const orbitron = Orbitron({
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});
const jura = Inter({
  weight: ['400', '700'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${jura.className} s:text-xs sm:text-sm md:text-base lg:text-lg 2xl:text-2xl`}
    >
      <body>
        <Providers>
          <Navbar />
          {/* <Home /> */}
          {children}
          {/* <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense> */}
        </Providers>
      </body>
    </html>
  );
}
